language: cpp
compiler: gcc

install:
  - cd ..
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - sudo make install
  - sudo apt-get install requirements.txt
  - cd ..
  - cd travis_arduino

script: 
  - ino build
